# This is Assignment 11 - Asha Karmakar

## Requirement 3

##### In your own words, describe the commonalities and differences between NumPy arrays and Pandas series.

Similarities:
- A specific index can be accessed from both a Panda series and a NumPy array using square bracket [] notation
- Both have array capabilities such as slicing

Differences:
- A Panda series is more flexible than a 1D NumPy array
- A Panda series allows you to add your own set of indices instead of just 0,1,2,3...

## Requirement 4

In [7]:
# Create a Pandas series named bill_names with American currency bill denominations as indices and President last names

import pandas as pd

bill_names = {1: 'Washington',
              2: 'Jefferson',
              5: 'Lincoln',
             10: 'Hamilton',
             20: 'Jackson',
             50: 'Grant',
            100: 'Franklin'}

pd.Series(bill_names)

1      Washington
2       Jefferson
5         Lincoln
10       Hamilton
20        Jackson
50          Grant
100      Franklin
dtype: object

## Requirement 5

In [8]:
# Create a Pandas series-as-dictionary beverages_dict. 
    
beverages_dict = {'Dr. Pepper': 'Dark soft drinks scare me',
                   'Lemonade': 'Very refreshing',
                   'Sprite': 'My favorite soft drink',
                   'Water': 'Necessary to live'}

beverages = pd.Series(beverages_dict)

# individual values via the keys
print ("Dr. Pepper:",beverages['Dr. Pepper'])

# multiple values via slicing
print (beverages['Lemonade':'Water'])

Dr. Pepper: Dark soft drinks scare me
Lemonade           Very refreshing
Sprite      My favorite soft drink
Water            Necessary to live
dtype: object


## Requirement 6

In [9]:
# Create a series-as-dictionary named population based on this information

population_dict = {'Chongquing': 15872000,
                   'Shanghai': 27058000,
                   'Tokyo': 37393000,
                   'Moscow': 12538000,
                   'Mexico City': 21782000,
                   'London': 9304000,
                   'New York': 18804000}

population = pd.Series(population_dict)
population

Chongquing     15872000
Shanghai       27058000
Tokyo          37393000
Moscow         12538000
Mexico City    21782000
London          9304000
New York       18804000
dtype: int64

## Requirement 7

In [10]:
# Create a Pandas series-as-dictionary named city_country with the cities in population and the countries for each city.

city_country_dict = {'Chongquing':'China',
                'Shanghai':'China',
                'Tokyo':'Japan',
                'Moscow':'Russia',
                'Mexico City': 'Mexico',
                'London': 'UK',
                'New York': 'USA'}

city_country = pd.Series(city_country_dict)
city_country

Chongquing      China
Shanghai        China
Tokyo           Japan
Moscow         Russia
Mexico City    Mexico
London             UK
New York          USA
dtype: object

## Requirement 8

In [11]:
# Create a Pandas dataframe object named city_dataframe from a dictionary of series objects

city_dataframe = pd.DataFrame({'population': population,'country': city_country})

# the .index property
print ("Index:", city_dataframe.index)

# the .columns property
print ("Columns:", city_dataframe.columns)

# the .keys() method
print ("Keys:", city_dataframe.keys())

Index: Index(['Chongquing', 'Shanghai', 'Tokyo', 'Moscow', 'Mexico City', 'London',
       'New York'],
      dtype='object')
Columns: Index(['population', 'country'], dtype='object')
Keys: Index(['population', 'country'], dtype='object')


## Requirement 9

In [12]:
#Create a Pandas series object named my_pd_series from a collection of string keys and collection of numeric values 

my_pd_series = data = pd.Series([13, 24, 35, 46],index=['a', 'b', 'c', 'd'])

# modifying a value based on key
my_pd_series['a']

# slicing by explicit index
print ("slicing by explicit index:\n", my_pd_series['a':'c'])

# slicing by implicit integer index
print ("\nslicing by implicit index:\n", my_pd_series[0:2])

# masking
print ("\nmasking:\n", my_pd_series[my_pd_series % 2 == 0])

# fancy indexing
print ("\nfancy indexing:\n", my_pd_series[['a','c']])

# loc[]
print ("\nloc[]:\n", my_pd_series.loc['b':'d'])

# iloc[]
print ("\niloc[]:\n", my_pd_series.iloc[2:4])

slicing by explicit index:
 a    13
b    24
c    35
dtype: int64

slicing by implicit index:
 a    13
b    24
dtype: int64

masking:
 b    24
d    46
dtype: int64

fancy indexing:
 a    13
c    35
dtype: int64

loc[]:
 b    24
c    35
d    46
dtype: int64

iloc[]:
 c    35
d    46
dtype: int64


## Requirement 10

In [13]:
# Using city_dataframe, demonstrate:

# access column via dictionary-style indexing of the column name
print ("access column via dictionary-style indexing of the column name:\n", city_dataframe['country'])

# access column via column names that are strings
print ("\naccess column via column names that are strings:\n", city_dataframe.country)

# add a new column to the city_dataframe named altitude.
altitude = pd.Series({'Chongquing': 801,
                      'Shanghai': 13.12,
                      'Tokyo': 131,
                      'Moscow': 512,
                      'Mexico City': 7382,
                      'London': 36,
                      'New York': 33})
city_dataframe['altitude'] = altitude
print ("\nadd a new column to the city_dataframe named altitude:\n", city_dataframe)

access column via dictionary-style indexing of the column name:
 Chongquing      China
Shanghai        China
Tokyo           Japan
Moscow         Russia
Mexico City    Mexico
London             UK
New York          USA
Name: country, dtype: object

access column via column names that are strings:
 Chongquing      China
Shanghai        China
Tokyo           Japan
Moscow         Russia
Mexico City    Mexico
London             UK
New York          USA
Name: country, dtype: object

add a new column to the city_dataframe named altitude:
              population country  altitude
Chongquing     15872000   China    801.00
Shanghai       27058000   China     13.12
Tokyo          37393000   Japan    131.00
Moscow         12538000  Russia    512.00
Mexico City    21782000  Mexico   7382.00
London          9304000      UK     36.00
New York       18804000     USA     33.00


## Requirement 11

In [14]:
# Create two Pandas series that when added using ‘+’ produce some NaN entries. 

a_series = pd.Series([1,2,3,4],index=['a','b','c','d'])
b_series = pd.Series([5,6,7,8],index=['c','d','e','f'])

print ("when added using ‘+’ produces some NaN entries:\n", a_series + b_series)

# Use the .add() method and a fill_value to replace the NaN entries
print ("\nuse the .add() method and a fill_value to replace the NaN entries:\n", a_series.add(b_series, fill_value = 0))

when added using ‘+’ produces some NaN entries:
 a     NaN
b     NaN
c     8.0
d    10.0
e     NaN
f     NaN
dtype: float64

use the .add() method and a fill_value to replace the NaN entries:
 a     1.0
b     2.0
c     8.0
d    10.0
e     7.0
f     8.0
dtype: float64


## Requirement 12

In [41]:
# Create two Pandas dataframes  

import numpy as np

a_df = pd.DataFrame(np.random.randint(0, 50, (2, 2)),columns=['A','B'])
b_df = pd.DataFrame(np.random.randint(0, 50, (2, 2)),columns=['B','C'])

print ("first array:\n",a_df)
print ("\nsecond array:\n",b_df)

# when added using ‘+’ produce some NaN entries. 
print ("\nadded using '+':\n", a_df + b_df)

# Use the .add() method and a fill_value of the mean of one of the dataframes to replace the NaN entries.
print ("\nadded using .add:\n", a_df.add(b_df, fill_value = a_df.stack().mean()))

first array:
     A   B
0  38  18
1   1   1

second array:
     B   C
0  40  27
1  18  19

added using '+':
     A   B   C
0 NaN  58 NaN
1 NaN  19 NaN

added using .add:
       A   B     C
0  52.5  58  41.5
1  15.5  19  33.5


## Requirement 13

In [36]:
# Create a two-dimensional NumPy array using:

import numpy as np
# ** What exactly does RandomState do? Does it store a set of random numbers? **
rng = np.random.RandomState(42)

A = rng.randint(5, 10, size=(4, 4))

print ("A:")
print (A)

# Demonstrate: subtracting row 0 of A from A

print ("\nsubtract row 0 of A from A:\n")
print (A-A[0])

A:
[[8 9 7 9]
 [9 6 7 7]
 [7 9 8 7]
 [9 6 8 6]]

subtract row 0 of A from A:

[[ 0  0  0  0]
 [ 1 -3  0 -2]
 [-1  0  1 -2]
 [ 1 -3  1 -3]]


## Requirement 14

In [39]:
# Create a Pandas dataframe using: 

df = pd.DataFrame(A, columns=list('QRST'))
print (df)

# Demonstrate: subtracting row 1 of df from df using df.iloc[1]

print ("\nsubtract row 1 of df from df using df.iloc[1]:\n")
print (df - df.iloc[1])

   Q  R  S  T
0  8  9  7  9
1  9  6  7  7
2  7  9  8  7
3  9  6  8  6

subtract row 1 of df from df using df.iloc[1]:

   Q  R  S  T
0 -1  3  0  2
1  0  0  0  0
2 -2  3  1  0
3  0  0  1 -1


## Requirement 15

##### Compare and contrast the two sentinel values Pandas uses to represent missing data.
The two sentinel values that Pandas uses to represent missing data are <b>none</b> and <b>NaN</b>.

<b>None</b> can only be used in arrays with object datatype (not just any NumPy/Pandas array).
<b>NaN</b>, which is an acronym for "not a number" is specifically used to represent missing <i>numerical</i> data.

If you added np.nan to an array, it will automatically be upcasted to the 'float64' datatype. In the process, any None in the array is also upcasted to a NaN.

## Requirement 16

In [43]:
# Demonstrate the %timeit difference between operations using Python objects and Python integers.

for t in ['object', 'int']:
    print("dtype =", t)
    %timeit np.arange(1E6, dtype=t).sum()
    print()

dtype = object
96.7 ms ± 2.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype = int
4.82 ms ± 679 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)



## Requirement 17

In [49]:
# Create a Pandas series containing null data. Use .isnull() to identify the entries that are null.

test = pd.Series(['string', False, np.nan, 4.8, 15, 'hello', None])
print (test.isnull())
test[test.isnull()]

0    False
1    False
2     True
3    False
4    False
5    False
6     True
dtype: bool


2     NaN
6    None
dtype: object

## Requirement 18

In [86]:
# Create a Pandas dataframe containing null values. Demonstrate:

test_df = pd.DataFrame([[1, 2, 3],
                        [4, np.nan, 6],
                        [np.nan, 8, 9],
                        [10, 11, 12]])
print (test_df)

# drop all rows containing a null value
print ("\ndrop all rows containing a null value:\n")
print (test_df.dropna())

# drop all columns containing a null value
print ("\ndrop all columns containing a null value:\n")
print (test_df.dropna(axis=1))

# drop only rows that contain all null values
test_df[0] = np.nan
print ("\ndrop only columns that contain all null values:\n")
print (test_df.dropna(axis=1 , how='all'))

# drop only columns that contain all null values
test_df[0] = [1,4,np.nan,10]
test_df.iloc[1] = np.nan
print ("\ndrop only rows that contain all null values:\n")
print (test_df.dropna(axis=0 , how='all'))

# replacing null with 0
print ("\nreplacing null with 0:\n")
print (test_df.fillna(0))

# forward fill
print ("\nforward fill:\n")
print (test_df.fillna(method='ffill'))

# backward fill 
print ("\nbackward fill:\n")
print (test_df.fillna(method='bfill'))

      0     1   2
0   1.0   2.0   3
1   4.0   NaN   6
2   NaN   8.0   9
3  10.0  11.0  12

drop all rows containing a null value:

      0     1   2
0   1.0   2.0   3
3  10.0  11.0  12

drop all columns containing a null value:

    2
0   3
1   6
2   9
3  12

drop only columns that contain all null values:

      1   2
0   2.0   3
1   NaN   6
2   8.0   9
3  11.0  12

drop only rows that contain all null values:

      0     1     2
0   1.0   2.0   3.0
2   NaN   8.0   9.0
3  10.0  11.0  12.0

replacing null with 0:

      0     1     2
0   1.0   2.0   3.0
1   0.0   0.0   0.0
2   0.0   8.0   9.0
3  10.0  11.0  12.0

forward fill:

      0     1     2
0   1.0   2.0   3.0
1   1.0   2.0   3.0
2   1.0   8.0   9.0
3  10.0  11.0  12.0

backward fill:

      0     1     2
0   1.0   2.0   3.0
1  10.0   8.0   9.0
2  10.0   8.0   9.0
3  10.0  11.0  12.0


## Requirement 19

In [21]:
# Demonstrate Pandas MultiIndex techniques:

import pandas as pd

index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]

populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561]

pop = pd.Series(populations, index=index)

# .from_tuples()
index = pd.MultiIndex.from_tuples(index)
print ("\n.from_tuples():\n")
print (index)

# .reindex()
pop = pop.reindex(index)
print ("\n.reindex():\n")
print (pop)

# .unstack()
pop_df = pop.unstack()
print ("\n.unstack():\n")
print (pop_df)

# .stack()
print ("\n.stack():\n")
print (pop_df.unstack())

# indexing and slicing
print ("\nindexing and slicing:\n")
print (pop['California',2000])
print (pop.loc['California':'New York'])


.from_tuples():

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

.reindex():

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

.unstack():

                2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

.stack():

2000  California    33871648
      New York      18976457
      Texas         20851820
2010  California    37253956
      New York      19378102
      Texas         25145561
dtype: int64

indexing and slicing:

33871648
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
dtype: int64


## Requirement 20

In [32]:
# Demonstrate concatenating two Pandas series. 

# One series contains automobile data. The other series contains motorcycle data.
autos = pd.Series(['Toyota','Porsche','Subaru'], index = ['RZA 372','WFZ 884','WCK 898'])
motorcycles = pd.Series(['Yamaha','Honda','Harley-Davidson'], index = ['UCL 870', 'ELD 657','XXT 682'])
pd.concat([autos, motorcycles])

RZA 372             Toyota
WFZ 884            Porsche
WCK 898             Subaru
UCL 870             Yamaha
ELD 657              Honda
XXT 682    Harley-Davidson
dtype: object

## Requirement 21

In [36]:
# Demonstrate concatenating two Pandas dataframe using the .append() method.

autos_df = pd.DataFrame(autos,columns=['Manufacturer'])
motorcycles_df = pd.DataFrame(motorcycles,columns=['Manufacturer'])

autos_df.append(motorcycles_df)

Manufacturer
RZA 372           Toyota
WFZ 884          Porsche
WCK 898           Subaru
UCL 870           Yamaha
ELD 657            Honda
XXT 682  Harley-Davidson

## Requirement 22

In [60]:
# Using Pandas dataframes, demonstrate the following joins:

df1 = pd.DataFrame({'team_member': ['Asha','Mindy','Garrett','Jerry','Tobi','Neha','Luke','Pranav','Kenna','Riley'],
                    'subteam': ['Software','Software','Software','Software','Hardware','Hardware',
                                'Hardware','Hardware', 'CAD', 'Marketing']})

df2 = pd.DataFrame({'team_member': ['Asha','Mindy','Garrett','Jerry','Tobi','Neha','Luke','Riley','Kenna','Pranav'],
                    'years': [3,2,2,1,2,2,3,4,1,2]})

df3 = pd.merge(df1, df2)

df4 = pd.DataFrame({'subteam': ['Software', 'Marketing', 'CAD', 'Hardware'],
                    'subteam_lead': ['Asha', 'Riley', 'Kenna', 'Pranav']})

df5 = pd.DataFrame({'subteam': ['Software', 'Marketing', 'CAD', 'Hardware'],
                    'weekday': ['Thursday', 'Tuesday', 'Wednesday', 'Monday']})

# one-to-one
print ("one-to-one:\n")
print (pd.merge(df1, df2))

# many-to-one: one of the two key columns contains duplicate entries
print ("\nmany-to-one:\n")
print (pd.merge(df3, df4))

# many-to-many: one of the two key columns contains duplicate entries
print ("\nmany-to-many:\n")
print (pd.merge(df1, df5))

one-to-one:

  team_member    subteam  years
0        Asha   Software      3
1       Mindy   Software      2
2     Garrett   Software      2
3       Jerry   Software      1
4        Tobi   Hardware      2
5        Neha   Hardware      2
6        Luke   Hardware      3
7      Pranav   Hardware      2
8       Kenna        CAD      1
9       Riley  Marketing      4

many-to-one:

  team_member    subteam  years subteam_lead
0        Asha   Software      3         Asha
1       Mindy   Software      2         Asha
2     Garrett   Software      2         Asha
3       Jerry   Software      1         Asha
4        Tobi   Hardware      2       Pranav
5        Neha   Hardware      2       Pranav
6        Luke   Hardware      3       Pranav
7      Pranav   Hardware      2       Pranav
8       Kenna        CAD      1        Kenna
9       Riley  Marketing      4        Riley

many-to-many:

  team_member    subteam    weekday
0        Asha   Software   Thursday
1       Mindy   Software   Thursday
2

## Requirement 23

In [71]:
# Using Pandas dataframes, demonstrate merge with the following keywords:

df6 = pd.DataFrame({'viperbot': ['Asha','Mindy','Garrett','Jerry','Tobi','Neha','Luke','Pranav','Kenna','Riley'],
                    'grade': [11,12,11,10,12,9,10,11,11,11]})

# on
print ("on:\n")
print (pd.merge(df1, df2, on='team_member'))

# left_on and right_on
print ("\nleft_on and right_on:\n")
print (pd.merge(df1, df6, left_on="team_member", right_on="viperbot"))

# left_index and right_index
df1a = df1.set_index('team_member')
df2a = df2.set_index('team_member')
print ("\nleft_index and right_index:\n")
print (pd.merge(df1a, df2a, left_index=True, right_index=True)) # what exactly does True mean here?


on:

  team_member    subteam  years
0        Asha   Software      3
1       Mindy   Software      2
2     Garrett   Software      2
3       Jerry   Software      1
4        Tobi   Hardware      2
5        Neha   Hardware      2
6        Luke   Hardware      3
7      Pranav   Hardware      2
8       Kenna        CAD      1
9       Riley  Marketing      4

left_on and right_on:

  team_member    subteam viperbot  grade
0        Asha   Software     Asha     11
1       Mindy   Software    Mindy     12
2     Garrett   Software  Garrett     11
3       Jerry   Software    Jerry     10
4        Tobi   Hardware     Tobi     12
5        Neha   Hardware     Neha      9
6        Luke   Hardware     Luke     10
7      Pranav   Hardware   Pranav     11
8       Kenna        CAD    Kenna     11
9       Riley  Marketing    Riley     11

left_index and right_index:

               subteam  years
team_member                  
Asha          Software      3
Mindy         Software      2
Garrett       Soft

## Requirement 24

Through completing Assignment 11 I learned how to create and manipulate pandas series and dataframes. I think the DataFrame is a really neat data structure and I like how it organizes the data so nicely. Overall, I was surprised by the large variety of built-in methods the pandas data structures offer; I think that's what makes it such a powerful and flexible tool for data manipulation. Earlier, when I was learning about PostgreSQL commands, I learned about the different types of table joins, which were kind of similar with the types of pandas DataFrame joins. There were a few things I was confused on: is a printed MultiIndex object supposed to be formatted like "MultiIndex(levels= --,labels= --)" ? Because when I printed the same MultiIndex object as the one in the book, it gave a differently formatted output. Another thing is, in the command "pd.merge(df1a, df2a, left_index=True, right_index=True)" what exactly does True mean?